version: '3.8'

services:
  springboot-1:
    container_name: springboot-1
    image: ${DOCKER_USER}/${DOCKER_REPO}:taxi-app  # Docker Hub에서 가져올 이미지
    ports:
      - "8080:8080"
    environment:
      TZ: "Asia/Seoul"
    depends_on:
#      - mariadb
      - redis

#  springboot-2:
#    container_name: springboot-2
#    image: ${DOCKER_USER}/${DOCKER_REPO}:taxi-app  # Docker Hub에서 가져올 이미지
#    ports:
#      - "8081:8080"
#    environment:
#      TZ: "Asia/Seoul"
#    depends_on:
#      #      - mariadb
#      - redis


#  mariadb:
#    image: mariadb:11
#    container_name: mariadb
#    environment:
#      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#      MYSQL_DATABASE: ${MYSQL_DATABASE}
#      MYSQL_USER: ${MYSQL_USER}
#      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#    ports:
#      - "3306:3306"
#    volumes:
#      - mariadb_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      TZ: "Asia/Seoul"
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    environment:
      TZ: "Asia/Seoul"
    depends_on:
      - springboot-1
      - springboot-2

volumes:
#  mariadb_data:
  redis_data:

